import textwrap
import os
from typing import TypedDict

from deepeval import evaluate
from deepeval.evaluate import AsyncConfig, ErrorConfig
from deepeval.metrics import GEval
from deepeval.metrics.g_eval import GEvalTemplate
from deepeval.models.llms.openrouter_model import OpenRouterModel
from deepeval.test_case import LLMTestCase, LLMTestCaseParams
from deepeval.metrics.g_eval import Rubric

class CustomGEvalTemplate(GEvalTemplate):
    @staticmethod
    def generate_evaluation_results(
        evaluation_steps: str,
        test_case_content: str,
        parameters: str,
        rubric: str | None = None,
        score_range: tuple[int, int] = (1, 5),
        _additional_context: str | None = None,
        multimodal: bool = False,
    ) -> str:
        del score_range, _additional_context, multimodal
        reasoning_expectation = (
            "Be specific and grounded in the evaluation steps and rubric."
            if rubric
            else "Be specific and grounded in the evaluation steps."
        )

        return  textwrap.dedent(f"""You are a Senior Legal Evaluator and expert attorney. Your job is to evaluate the quality of a response generated by an AI Legal Assistant by comparing it against a verified "Gold Standard" answer.
            
            You will be provided with:
            1. A Legal Question.
            2. A Gold Standard Answer (created by human experts).
            3. A System Response (generated by the AI).
            You must rate the System Response on a scale of 1 to 5 based on how well the legal reasoning and factual content align with the Gold Standard.
            
            - **Content Focus:** Focus ONLY on the textual content, legal accuracy, and reasoning.
            - **Strict Adherence:** The Gold Standard is the absolute truth. If the System Response contradicts the Gold Standard, it is wrong, even if you believe the Gold Standard might be incomplete.
            - **Completeness:** The System Response must contain the critical legal elements present in the Gold Standard.

            Assess the response below and return a JSON object with two fields:

            - `"score"`: an integer between 1 and 5.
                **1 - Critical Failure / Incorrect**
                The response implies the opposite legal conclusion to the Gold Standard, provides dangerous legal advice, or is completely irrelevant to the question.
                **2 - Poor / Significant Omissions**
                The conclusion is vague or partially incorrect. It misses the central legal argument or key fact found in the Gold Standard. It may contain hallucinations.
                **3 - Acceptable / Partially Complete**
                The response captures the general legal principle correctly but misses important nuances, exceptions, or specific details present in the Gold Standard. It is legally safe but not comprehensive.
                **4 - Good / Mostly Accurate**
                The response aligns with the Gold Standard in conclusion and reasoning. It may miss very minor details that do not alter the legal outcome.
                **5 - Excellent / Semantically Equivalent**
                The response is logically and factually equivalent to the Gold Standard. It captures all key legal elements, reasoning, and conclusions. (Difference in wording or structure is acceptable).
            - `"reason"`: a brief explanation for why the score was given. This must mention specific strengths or shortcomings, referencing relevant details from the input. Do **not** quote the score itself in the explanation.

            Your explanation should:
            - {reasoning_expectation}
            - Mention key details from the test case parameters.
            - Be concise, clear, and focused on the evaluation logic.

            Only return valid JSON. Do **not** include any extra commentary or text.

            ---
            Test Case:
            {test_case_content}

            Parameters:
            {parameters}

            ---
            **Example JSON:**
            {{
                "reason": "your concise and informative reason here",
                "score": 1
            }}

            JSON:
            """
        )


class CorrectnessInput(TypedDict):
    id: str
    query: str
    prediction: str
    ref: str


class CorrectnessResult(TypedDict):
    scores: dict[str, float]
    failed_eval_ids: list[str]
    failure_reasons: dict[str, str]
    evaluation_reasons: dict[str, str]


class JudgeConfig(TypedDict, total=False):
    model: str
    api_key: str
    providers: list[str]


def _create_correctness_metric(
    judge_config: JudgeConfig | None = None,
) -> GEval:
    config = judge_config or {}
    judge_model_name = config.get("model")
    if judge_model_name is None or not str(judge_model_name).strip():
        raise ValueError("Model is required. Set judge_config['model'].")

    provider_only = config.get("providers")
    judge_kwargs: dict[str, object] = {"model": judge_model_name}

    api_key = config.get("api_key") or os.getenv("OPENROUTER_API_KEY")
    if api_key is None or not str(api_key).strip():
        raise ValueError(
            "OpenRouter API key is required. Set judge_config['api_key'] or OPENROUTER_API_KEY."
        )
    judge_kwargs["api_key"] = api_key

    if provider_only is not None:
        provider_payload: dict[str, object] = {"only": provider_only}
        judge_kwargs["generation_kwargs"] = {
            "extra_body": {"provider": provider_payload}
        }

    geval_metric = GEval(
         name="Correctness",
         evaluation_steps=[
                "Compare the actual output directly with the expected output to verify factual accuracy.",
                "Check if all elements mentioned in the expected output are present and correctly represented in the actual output.",
                "Assess if there are any discrepancies in details, values, or information between the actual and expected outputs.",
            ],
        rubric=[
            Rubric(score_range=(1,1), expected_outcome=" Critical Failure / Incorrect."),
            Rubric(score_range=(2,2), expected_outcome="Poor / Significant Omissions."),
            Rubric(score_range=(3,3), expected_outcome="Acceptable / Partially Complete."),
            Rubric(score_range=(4,4), expected_outcome="Good / Mostly Accurate."),
            Rubric(score_range=(5,5), expected_outcome="Excellent / Semantically Equivalent.")
            ],
        evaluation_params=[
            LLMTestCaseParams.INPUT,
            LLMTestCaseParams.ACTUAL_OUTPUT,
            LLMTestCaseParams.EXPECTED_OUTPUT,
        ],
        model=OpenRouterModel(**judge_kwargs),
        evaluation_template=CustomGEvalTemplate,
    )

    return geval_metric


def _extract_score(test_result: object) -> float | None:
    metrics_data = getattr(test_result, "metrics_data", None)
    if isinstance(metrics_data, list) and metrics_data:
        first = metrics_data[0]
        score = getattr(first, "score", None)
        if score is not None:
            return float(score)

    score = getattr(test_result, "score", None)
    return float(score) if score is not None else None


def _extract_failure_reason(test_result: object) -> str:
    for attr in ("error", "failure_reason", "reason"):
        value = getattr(test_result, attr, None)
        if value:
            return str(value)
    return "missing_score"


def _extract_evaluation_reason(test_result: object) -> str | None:
    metrics_data = getattr(test_result, "metrics_data", None)
    if isinstance(metrics_data, list) and metrics_data:
        first = metrics_data[0]
        reason = getattr(first, "reason", None)
        if reason:
            return str(reason)

    reason = getattr(test_result, "reason", None)
    if reason:
        return str(reason)
    return None


def deepeval_correctness(
    input_rows: list[CorrectnessInput],
    judge_config: JudgeConfig | None = None,
) -> CorrectnessResult:
    """
    Score correctness for multiple rows shaped like:
    [{"id": str, "query": str, "prediction": str, "ref": str}]
    """
    test_cases = [
        LLMTestCase(
            input=input_row["query"],
            actual_output=input_row["prediction"],
            expected_output=input_row["ref"],
        )
        for input_row in input_rows
    ]

    correctness_metric = _create_correctness_metric(
        judge_config=judge_config,
    )
    score_range = correctness_metric.score_range
    if (
        isinstance(score_range, tuple)
        and len(score_range) == 2
        and isinstance(score_range[0], (int, float))
        and isinstance(score_range[1], (int, float))
        and float(score_range[0]) != float(score_range[1])
    ):
        score_min = float(score_range[0])
        score_max = float(score_range[1])
    else:
        score_min, score_max = 1.0, 5.0

    def _scale_to_metric_range(raw_score: float) -> float:
        # DeepEval may return normalized scores in [0, 1]; scale into metric score_range.
        if 0.0 <= raw_score <= 1.0:
            return score_min + raw_score * (score_max - score_min)
        return raw_score

    results = evaluate(
        test_cases=test_cases,
        metrics=[correctness_metric],
        async_config=AsyncConfig(
            run_async=True,
            max_concurrent=5,
            throttle_value=3,
        ),
        error_config=ErrorConfig(
            ignore_errors=True,
            skip_on_missing_params=True,
        ),
    )

    test_results = getattr(results, "test_results", None)
    if not isinstance(test_results, list):
        test_results = []

    scores: dict[str, float] = {}
    failed_eval_ids: list[str] = []
    failure_reasons: dict[str, str] = {}
    evaluation_reasons: dict[str, str] = {}
    for index, input_row in enumerate(input_rows):
        case_id = input_row["id"]
        if index < len(test_results):
            eval_reason = _extract_evaluation_reason(test_results[index])
            if eval_reason:
                evaluation_reasons[case_id] = eval_reason
            score = _extract_score(test_results[index])
            if score is not None:
                scores[case_id] = _scale_to_metric_range(score)
            else:
                failed_eval_ids.append(case_id)
                failure_reasons[case_id] = _extract_failure_reason(test_results[index])
        else:
            failed_eval_ids.append(case_id)
            failure_reasons[case_id] = "missing_test_result"
    return {
        "scores": scores,
        "failed_eval_ids": failed_eval_ids,
        "failure_reasons": failure_reasons,
        "evaluation_reasons": evaluation_reasons,
    }
